### PR TITLE
use quote in facebook url rather than description

### PR DESCRIPTION
**Pull request by knoxjeffrey**
Facebook no longer allows the user to pass custom params. However, quote will work so I've changed description to quote

### CODE REVIEW

**Comment by huacnlee** [comment]
Just released 1.0.0

fix #141

**Comment by Adeering** [comment]
Using 1.0.0 and I still get this error

**Comment by amed-kino** [comment]
There is still error here with rails `5.1`

Gemfile.lock: `social-share-button (1.0.0)`

Url: `_fb_/sharer/sharer.php?u=google.com&display=popup&quote=%20`

-----
screen shot 2017-09-18 at 12 44 39

**Comment by TranBaVinhSon** [comment]
I still have this error, has any solution?

**Comment by amed-kino** [comment]
This is a temporary solution until solving @TranBaVinhSon 
```
<div class="social-share-button">
  <a class="ssb-icon ssb-facebook" href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" target="_blank"></a>
</div>
<%= social_share_button_tag %>
```

**Comment by austinarchibald** [comment]
To build on @amed-kino 's temp solution, you can disable facebook in social_share_button.rb and to get all buttons in one line do this:

```
<div style="display: inline-flex;">
  <div class="social-share-button">
    <a class="ssb-icon ssb-facebook" href="https://www.facebook.com/sharer/sharer.php?u=http://example.com" target="popup" onclick="window.open('https://www.facebook.com/sharer/sharer.php?u=http://example.com','popup','width=555,height=400'); return false;"></a>
  </div>
  <%= social_share_button_tag("custom message", :url => "http://example.com") %>
</div>
```

**Pull request merged**
