### PR TITLE
Fixed quote breaking facebook share

### PR DESCRIPTION
**Pull request by FrankelJb**

### CODE REVIEW

**Comment by jasonfb** [comment]
this seem inconsistent with note left on README here: https://github.com/huacnlee/social-share-button#facebook-needs-the-description-added

we were assuming the requirement is on Facebook's end? this code assumes this is not true and FB does not require the description

**Comment by jasonfb** [comment]
a few observations indicate to us that this code change is correct and the note on the README is wrong, perhaps the only problem is when #{desc} is an empty string

to preserve the existing functionality maybe something like this

```
http://www.facebook.com/sharer/sharer.php?u=#{url}&display=popup#{("&quote=" + desc) if desc}
```

**Comment by anna-kalina** [comment]
It work's fine without extra space
`desc = encodeURIComponent($parent.data("desc") || '')`

**Comment by Federico-G** [comment]
Any news about this?

**Pull request closed without merging**
